# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Trevor's Note
email: trevor.devalle@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Questo è sito è un repository di appunti per tutte le materie di cui sono interessato o che sono obbligato ad interessarmi a causa dell'università. 
  Spero che vi piaccia. Un giorno potrei pure metterci una grafica che vada oltrequesto spazio minimale. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "  treevil.github.io/notes" 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: 
  - bower_components/MathJax
  - node_modules
